"use client";

import { useState, useCallback, useMemo } from "react";
import { motion } from "framer-motion";
import { Experience } from "@/lib/types";
import { ShareModal } from "./ShareModal";
import { RecipeRolodex } from "../gallery/RecipeRolodex";

export function FullMenuScreen({
  experience,
}: {
  experience: Experience;
}) {
  const p = experience.palette;
  const courses = experience.courses ?? [];
  const tracks = experience.tracks ?? [];
  const [showShare, setShowShare] = useState(false);
  const [showRecipes, setShowRecipes] = useState(false);
  const hasCourses = courses.length > 0;

  // Build YouTube playlist URL from track names
  const youtubePlaylistUrl = useMemo(() => {
    if (!tracks.length) return null;
    const query = tracks
      .map((t) => `${t.artist} - ${t.name}`)
      .join(", ");
    return `https://www.youtube.com/results?search_query=${encodeURIComponent(query + " playlist")}`;
  }, [tracks]);

  const downloadAllRecipes = useCallback(
    (e: React.MouseEvent) => {
      e.stopPropagation();
      const lines: string[] = [];
      lines.push("═".repeat(55));
      lines.push(`  SONIC SOMMELIER — ${experience.title.toUpperCase()}`);
      lines.push(`  ${experience.subtitle}`);
      lines.push("═".repeat(55));
      lines.push("");

      courses.forEach((c, i) => {
        lines.push(`${"─".repeat(55)}`);
        lines.push(`  COURSE ${c.courseNumber}: ${c.courseType}`);
        lines.push(`  ${c.dishName}`);
        lines.push(`${"─".repeat(55)}`);
        if (c.dishDescription) {
          lines.push(`  ${c.dishDescription}`);
          lines.push("");
        }
        if (c.prepTime || c.servings) {
          const meta: string[] = [];
          if (c.prepTime) meta.push(`Prep: ${c.prepTime} min`);
          if (c.servings) meta.push(`Serves: ${c.servings}`);
          lines.push(`  ${meta.join("  |  ")}`);
          lines.push("");
        }
        if (tracks[i]) {
          lines.push(`  Paired with: "${tracks[i].name}" by ${tracks[i].artist}`);
          lines.push("");
        }
        if (c.ingredients?.length) {
          lines.push("  INGREDIENTS:");
          c.ingredients.forEach((ing) => lines.push(`    • ${ing.amount}`));
          lines.push("");
        }
        if (c.instructions?.length) {
          lines.push("  INSTRUCTIONS:");
          c.instructions.forEach((step, j) => {
            lines.push(`    ${j + 1}. ${step}`);
          });
          lines.push("");
        }
        if (c.beverageName) {
          lines.push(`  PAIRING: ${c.beverageName}`);
          if (c.tastingNote) lines.push(`  ${c.tastingNote}`);
          lines.push("");
        }
        lines.push("");
      });

      lines.push("═".repeat(55));
      lines.push("  Generated by Sonic Sommelier");
      lines.push("═".repeat(55));

      const blob = new Blob([lines.join("\n")], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${experience.title.toLowerCase().replace(/\s+/g, "-").slice(0, 40)}-recipes.txt`;
      a.click();
      URL.revokeObjectURL(url);
    },
    [experience, courses, tracks]
  );

  return (
    <>
      <div
        className="absolute inset-0 overflow-y-auto"
        style={{
          background: `linear-gradient(to bottom, ${p.secondary}, ${p.primary}33)`,
        }}
      >
        <div className="min-h-full flex flex-col md:flex-row" style={{ padding: "60px 0 40px" }}>

          {/* ═══ LEFT COLUMN — Menu ═══ */}
          <div className="flex-1 px-7 md:px-10 md:max-w-[55%]">
            {/* Header */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2, duration: 0.6 }}
              className="mb-8"
            >
              <div
                className="font-['JetBrains_Mono'] text-[9px] tracking-[0.35em] uppercase mb-3"
                style={{ color: p.accent + "66" }}
              >
                The Complete Menu
              </div>
              <h2
                className="font-['Playfair_Display'] text-[28px] md:text-[36px] italic font-normal leading-[1.1] m-0"
                style={{ color: p.text }}
              >
                {experience.title}
              </h2>
              <p
                className="font-['Instrument_Serif'] text-[14px] italic mt-2"
                style={{ color: p.text + "55" }}
              >
                {experience.subtitle}
              </p>
            </motion.div>

            {/* Course list */}
            <div className="relative">
              {courses.map((c, i) => (
                <motion.div
                  key={c.courseNumber}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.4 + i * 0.12, duration: 0.5 }}
                  className="flex gap-4 mb-5 pb-5"
                  style={{
                    borderBottom: i < courses.length - 1 ? `1px solid ${p.text}08` : "none",
                  }}
                >
                  <div
                    className="font-['JetBrains_Mono'] text-[11px] w-5 flex-shrink-0 pt-0.5"
                    style={{ color: p.accent + "55" }}
                  >
                    {String(c.courseNumber).padStart(2, "0")}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div
                      className="font-['Space_Grotesk'] text-[9px] tracking-[0.2em] uppercase mb-1"
                      style={{ color: p.text + "33" }}
                    >
                      {c.courseType}
                    </div>
                    <div
                      className="font-['Playfair_Display'] text-lg leading-[1.2] mb-1"
                      style={{ color: p.text }}
                    >
                      {c.dishName}
                    </div>
                    {c.beverageName && (
                      <div
                        className="font-['Instrument_Serif'] text-[13px] italic"
                        style={{ color: p.accent + "77" }}
                      >
                        {c.beverageName}
                      </div>
                    )}
                    {tracks[i] && (
                      <div
                        className="font-['Space_Grotesk'] text-[11px] mt-1.5 flex items-center gap-1.5"
                        style={{ color: p.text + "33" }}
                      >
                        <span style={{ fontSize: "10px" }}>&#9835;</span>
                        <span className="truncate">
                          {tracks[i].name} &mdash; {tracks[i].artist}
                        </span>
                      </div>
                    )}
                  </div>
                </motion.div>
              ))}
            </div>

            {/* YouTube playlist link (mobile — below menu) */}
            {youtubePlaylistUrl && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 1.0, duration: 0.5 }}
                className="md:hidden mb-6"
              >
                <a
                  href={youtubePlaylistUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  onClick={(e) => e.stopPropagation()}
                  className="flex items-center gap-2.5 rounded-xl px-4 py-3 no-underline transition-colors"
                  style={{
                    background: "rgba(255,0,0,0.08)",
                    border: "1px solid rgba(255,0,0,0.12)",
                  }}
                >
                  <span style={{ fontSize: "18px", color: "#ff4444" }}>&#9654;</span>
                  <div>
                    <div
                      className="font-['Space_Grotesk'] text-[11px] tracking-[0.1em] uppercase font-medium"
                      style={{ color: p.text + "bb" }}
                    >
                      Listen on YouTube
                    </div>
                    <div
                      className="font-['Space_Grotesk'] text-[10px]"
                      style={{ color: p.text + "44" }}
                    >
                      {tracks.length} tracks curated for this experience
                    </div>
                  </div>
                </a>
              </motion.div>
            )}
          </div>

          {/* ═══ RIGHT COLUMN — Poster + Actions ═══ */}
          <div className="px-7 md:px-10 md:w-[45%] md:flex md:flex-col md:items-center md:justify-start md:pt-4">

            {/* Poster */}
            {experience.shareImageUrl && (
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.6, duration: 0.6 }}
                className="mb-6 w-full max-w-[360px]"
              >
                <div
                  className="rounded-2xl overflow-hidden shadow-2xl"
                  style={{
                    border: `1px solid ${p.accent}15`,
                    boxShadow: `0 20px 60px rgba(0,0,0,0.4), 0 0 40px ${p.accent}08`,
                  }}
                >
                  <img
                    src={experience.shareImageUrl}
                    alt={`${experience.title} poster`}
                    className="w-full h-auto block"
                  />
                </div>
              </motion.div>
            )}

            {/* YouTube playlist link (desktop — right column) */}
            {youtubePlaylistUrl && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 1.0, duration: 0.5 }}
                className="hidden md:block w-full max-w-[360px] mb-5"
              >
                <a
                  href={youtubePlaylistUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  onClick={(e) => e.stopPropagation()}
                  className="flex items-center gap-3 rounded-xl px-4 py-3.5 no-underline transition-colors"
                  style={{
                    background: "rgba(255,0,0,0.08)",
                    border: "1px solid rgba(255,0,0,0.12)",
                  }}
                >
                  <span style={{ fontSize: "20px", color: "#ff4444" }}>&#9654;</span>
                  <div>
                    <div
                      className="font-['Space_Grotesk'] text-[12px] tracking-[0.1em] uppercase font-medium"
                      style={{ color: p.text + "bb" }}
                    >
                      Listen on YouTube
                    </div>
                    <div
                      className="font-['Space_Grotesk'] text-[10px] mt-0.5"
                      style={{ color: p.text + "44" }}
                    >
                      {tracks.length} tracks curated for this experience
                    </div>
                  </div>
                </a>
              </motion.div>
            )}

            {/* Divider */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 1.2, duration: 0.5 }}
              className="my-4 mx-auto"
              style={{
                width: "40px",
                height: "1px",
                backgroundColor: p.accent + "33",
              }}
            />

            {/* Actions */}
            <motion.div
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 1.3, duration: 0.5 }}
              className="flex flex-col gap-3 items-center w-full max-w-[360px]"
            >
              {hasCourses && (
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    setShowRecipes(true);
                  }}
                  aria-label="View recipe rolodex"
                  className="w-full font-['Space_Grotesk'] text-[12px] tracking-[0.12em] uppercase rounded-full px-7 py-3.5 cursor-pointer border-none transition-colors duration-200 font-medium"
                  style={{
                    color: p.secondary,
                    backgroundColor: p.accent,
                  }}
                >
                  &#127860; View Recipes
                </button>
              )}
              {courses.some((c) => c.ingredients?.length) && (
                <button
                  onClick={downloadAllRecipes}
                  aria-label="Download all recipe cards"
                  className="w-full font-['Space_Grotesk'] text-[11px] tracking-[0.12em] uppercase rounded-full px-7 py-3 cursor-pointer bg-transparent transition-colors duration-200"
                  style={{
                    color: p.text + "77",
                    border: `1px solid ${p.text}15`,
                  }}
                >
                  &#8595; Download All Recipes
                </button>
              )}
              {experience.shareSlug && (
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    setShowShare(true);
                  }}
                  aria-label="Share this experience"
                  className="w-full font-['Space_Grotesk'] text-[11px] tracking-[0.12em] uppercase rounded-full px-7 py-3 cursor-pointer border-none transition-colors duration-200"
                  style={{
                    color: p.secondary,
                    backgroundColor: p.accent,
                  }}
                >
                  Share &amp; Download Poster
                </button>
              )}
            </motion.div>
          </div>
        </div>
      </div>

      <ShareModal
        isOpen={showShare}
        onClose={() => setShowShare(false)}
        experienceId={experience._id as any}
        shareSlug={experience.shareSlug}
        shareImageUrl={experience.shareImageUrl}
        title={experience.title}
        palette={p}
      />

      {showRecipes && experience.courses && experience.tracks && (
        <RecipeRolodex
          isOpen={showRecipes}
          onClose={() => setShowRecipes(false)}
          courses={experience.courses}
          tracks={experience.tracks}
          palette={p}
          title={experience.title}
        />
      )}
    </>
  );
}
