"use client";

import { useState, useCallback, useEffect } from "react";
import { createPortal } from "react-dom";
import { Course, Track, Palette } from "@/lib/types";

interface RecipeRolodexProps {
  isOpen: boolean;
  onClose: () => void;
  courses: Course[];
  tracks: Track[];
  palette: Palette;
  title: string;
}

export function RecipeRolodex({
  isOpen,
  onClose,
  courses,
  tracks,
  palette: p,
  title,
}: RecipeRolodexProps) {
  const [currentIndex, setCurrentIndex] = useState(0);

  // Lock body scroll when open
  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = "hidden";
      return () => {
        document.body.style.overflow = "";
      };
    }
  }, [isOpen]);

  const navigate = useCallback(
    (dir: number) => {
      const next = currentIndex + dir;
      if (next < 0 || next >= courses.length) return;
      setCurrentIndex(next);
    },
    [currentIndex, courses.length]
  );

  // Keyboard navigation
  useEffect(() => {
    if (!isOpen) return;
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
      if (e.key === "ArrowLeft") navigate(-1);
      if (e.key === "ArrowRight") navigate(1);
    };
    window.addEventListener("keydown", handleKey);
    return () => window.removeEventListener("keydown", handleKey);
  }, [isOpen, onClose, navigate]);

  const downloadRecipe = useCallback(
    (c: Course) => {
      const lines: string[] = [];
      lines.push("═".repeat(50));
      lines.push(`  SONIC SOMMELIER — RECIPE CARD`);
      lines.push("═".repeat(50));
      lines.push("");
      lines.push(`  Course ${c.courseNumber}: ${c.courseType}`);
      lines.push(`  ${c.dishName}`);
      lines.push("");
      if (c.dishDescription) {
        lines.push(`  ${c.dishDescription}`);
        lines.push("");
      }
      if (c.prepTime || c.servings) {
        const meta: string[] = [];
        if (c.prepTime) meta.push(`Prep: ${c.prepTime} min`);
        if (c.servings) meta.push(`Serves: ${c.servings}`);
        lines.push(`  ${meta.join("  |  ")}`);
        lines.push("");
      }
      if (c.ingredients?.length) {
        lines.push("─".repeat(50));
        lines.push("  INGREDIENTS");
        lines.push("─".repeat(50));
        c.ingredients.forEach((ing) => lines.push(`  • ${ing.amount}`));
        lines.push("");
      }
      if (c.instructions?.length) {
        lines.push("─".repeat(50));
        lines.push("  INSTRUCTIONS");
        lines.push("─".repeat(50));
        c.instructions.forEach((step, i) => {
          lines.push(`  ${i + 1}. ${step}`);
          lines.push("");
        });
      }
      if (c.beverageName) {
        lines.push("─".repeat(50));
        lines.push("  PAIRING");
        lines.push("─".repeat(50));
        lines.push(`  ${c.beverageName}`);
        if (c.tastingNote) lines.push(`  ${c.tastingNote}`);
        lines.push("");
      }
      lines.push("═".repeat(50));
      lines.push("  Generated by Sonic Sommelier");
      lines.push("═".repeat(50));

      const blob = new Blob([lines.join("\n")], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `recipe-${c.courseNumber}-${c.dishName
        .toLowerCase()
        .replace(/\s+/g, "-")
        .slice(0, 30)}.txt`;
      a.click();
      URL.revokeObjectURL(url);
    },
    []
  );

  if (!isOpen || courses.length === 0) return null;

  const course = courses[currentIndex];
  const trackIndex = course.courseNumber - 1;
  const track = tracks[trackIndex];

  return createPortal(
    <div
      className="fixed inset-0 z-[200] flex flex-col"
      style={{ backgroundColor: "#080808" }}
      onClick={(e) => e.stopPropagation()}
    >
      {/* Fixed header */}
      <div
        className="flex-shrink-0 px-6 pt-5 pb-4"
        style={{
          backgroundColor: "#080808",
          borderBottom: `1px solid ${p.text}0a`,
        }}
      >
        <div className="max-w-2xl mx-auto">
          <div className="flex items-center justify-between mb-4">
            <div>
              <div
                className="font-['JetBrains_Mono'] text-[9px] tracking-[0.3em] uppercase mb-1"
                style={{ color: p.accent + "66" }}
              >
                Recipe Rolodex
              </div>
              <div
                className="font-['Playfair_Display'] text-lg italic"
                style={{ color: p.text + "cc" }}
              >
                {title}
              </div>
            </div>
            <button
              onClick={onClose}
              className="w-10 h-10 rounded-full flex items-center justify-center text-xl border-none cursor-pointer"
              style={{
                color: p.text + "77",
                backgroundColor: p.text + "10",
              }}
            >
              &times;
            </button>
          </div>

          {/* Tab bar */}
          <div className="flex gap-1">
            {courses.map((c, i) => (
              <button
                key={i}
                onClick={() => setCurrentIndex(i)}
                className="flex-1 py-2 rounded-lg border-none cursor-pointer transition-all duration-200"
                style={{
                  backgroundColor:
                    i === currentIndex ? p.accent + "22" : "transparent",
                  borderBottom:
                    i === currentIndex
                      ? `2px solid ${p.accent}`
                      : `2px solid transparent`,
                }}
              >
                <span
                  className="font-['Space_Grotesk'] text-[10px] tracking-[0.1em] uppercase"
                  style={{
                    color:
                      i === currentIndex ? p.accent : p.text + "33",
                  }}
                >
                  {c.courseType}
                </span>
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Scrollable content */}
      <div className="flex-1 overflow-y-auto">
        <div className="max-w-2xl mx-auto px-6 py-6">
          {/* Course image */}
          {course.aiImageUrl && (
            <div
              className="h-48 md:h-64 rounded-2xl overflow-hidden relative mb-6"
              style={{
                backgroundImage: `url(${course.aiImageUrl})`,
                backgroundSize: "cover",
                backgroundPosition: "center",
              }}
            >
              <div
                className="absolute inset-0"
                style={{
                  background: `linear-gradient(to bottom, transparent 40%, #080808 100%)`,
                }}
              />
              {track?.albumArt && (
                <div
                  className="absolute bottom-4 right-4 w-14 h-14 rounded-lg shadow-xl"
                  style={{
                    backgroundImage: `url(${track.albumArt})`,
                    backgroundSize: "cover",
                    border: "2px solid #080808",
                  }}
                />
              )}
            </div>
          )}

          {/* Course label */}
          <div
            className="font-['JetBrains_Mono'] text-[9px] tracking-[0.3em] uppercase mb-2"
            style={{ color: p.accent + "66" }}
          >
            Course {course.courseNumber} &middot; {course.courseType}
          </div>

          {/* Dish name */}
          <h3
            className="font-['Playfair_Display'] text-[28px] md:text-[34px] leading-[1.15] font-normal m-0 mb-3"
            style={{ color: p.text }}
          >
            {course.recipeTitle || course.dishName}
          </h3>

          {/* Description */}
          {course.dishDescription && (
            <p
              className="font-['Instrument_Serif'] text-[15px] italic leading-[1.6] mb-5"
              style={{ color: p.text + "77" }}
            >
              {course.dishDescription}
            </p>
          )}

          {/* Meta row */}
          {(course.prepTime || course.servings) && (
            <div
              className="flex gap-5 mb-6 font-['Space_Grotesk'] text-[12px]"
              style={{ color: p.text + "55" }}
            >
              {course.prepTime && (
                <span>&#9201; {course.prepTime} min</span>
              )}
              {course.servings && (
                <span>&#127869; {course.servings} servings</span>
              )}
            </div>
          )}

          {/* Track pairing */}
          {track && (
            <div
              className="flex items-center gap-3 mb-6 rounded-xl p-3.5"
              style={{
                background: p.text + "06",
                border: `1px solid ${p.text}0a`,
              }}
            >
              {track.albumArt && (
                <div
                  className="w-11 h-11 rounded-md flex-shrink-0"
                  style={{
                    backgroundImage: `url(${track.albumArt})`,
                    backgroundSize: "cover",
                  }}
                />
              )}
              <div className="min-w-0">
                <div
                  className="font-['Space_Grotesk'] text-[13px] font-medium truncate"
                  style={{ color: p.text + "bb" }}
                >
                  {track.name}
                </div>
                <div
                  className="font-['Space_Grotesk'] text-[11px] truncate"
                  style={{ color: p.text + "55" }}
                >
                  {track.artist} &middot; {track.album}
                </div>
              </div>
            </div>
          )}

          {/* Two-column layout for ingredients + instructions on wider screens */}
          <div className="md:flex md:gap-8">
            {/* Ingredients */}
            {course.ingredients && course.ingredients.length > 0 && (
              <div className="mb-6 md:w-2/5 md:flex-shrink-0">
                <h4
                  className="font-['Space_Grotesk'] text-[10px] tracking-[0.2em] uppercase mb-3 m-0"
                  style={{ color: p.accent + "88" }}
                >
                  Ingredients
                </h4>
                <ul className="list-none p-0 m-0">
                  {course.ingredients.map((ing, i) => (
                    <li
                      key={i}
                      className="font-['Space_Grotesk'] text-[13px] py-2"
                      style={{
                        color: p.text + "cc",
                        borderBottom: `1px solid ${p.text}08`,
                      }}
                    >
                      {ing.amount}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Instructions */}
            {course.instructions && course.instructions.length > 0 && (
              <div className="mb-6 md:flex-1">
                <h4
                  className="font-['Space_Grotesk'] text-[10px] tracking-[0.2em] uppercase mb-3 m-0"
                  style={{ color: p.accent + "88" }}
                >
                  Instructions
                </h4>
                <ol className="list-none p-0 m-0">
                  {course.instructions.map((step, i) => (
                    <li key={i} className="flex gap-3 mb-4">
                      <span
                        className="font-['JetBrains_Mono'] text-[11px] flex-shrink-0 mt-0.5 w-6 h-6 rounded-full flex items-center justify-center"
                        style={{
                          color: p.accent,
                          backgroundColor: p.accent + "12",
                        }}
                      >
                        {i + 1}
                      </span>
                      <p
                        className="font-['Space_Grotesk'] text-[13px] leading-[1.7] m-0"
                        style={{ color: p.text + "bb" }}
                      >
                        {step}
                      </p>
                    </li>
                  ))}
                </ol>
              </div>
            )}
          </div>

          {/* No recipe fallback */}
          {(!course.ingredients || course.ingredients.length === 0) &&
            (!course.instructions || course.instructions.length === 0) && (
              <div
                className="rounded-xl p-8 text-center mb-6"
                style={{
                  background: p.text + "06",
                  border: `1px solid ${p.text}0a`,
                }}
              >
                <div className="text-3xl mb-3">&#127860;</div>
                <p
                  className="font-['Instrument_Serif'] text-[15px] italic m-0"
                  style={{ color: p.text + "44" }}
                >
                  Recipe will be available in new experiences
                </p>
              </div>
            )}

          {/* Wine pairing */}
          {course.beverageName && (
            <div
              className="rounded-xl p-5 mb-6"
              style={{
                background: p.accent + "08",
                border: `1px solid ${p.accent}15`,
              }}
            >
              <div className="flex items-center gap-2 mb-2">
                <span
                  className="font-['JetBrains_Mono'] text-[9px] tracking-[0.15em] uppercase"
                  style={{ color: p.accent + "88" }}
                >
                  Wine Pairing
                </span>
                {course.servingTemp && (
                  <span
                    className="font-['JetBrains_Mono'] text-[9px]"
                    style={{ color: p.text + "44" }}
                  >
                    {course.servingTemp}
                  </span>
                )}
              </div>
              <div
                className="font-['Instrument_Serif'] text-[16px] mb-1.5"
                style={{ color: p.text }}
              >
                {course.beverageName}
              </div>
              {course.tastingNote && (
                <p
                  className="font-['Space_Grotesk'] text-[12px] leading-[1.6] m-0"
                  style={{ color: p.text + "66" }}
                >
                  {course.tastingNote}
                </p>
              )}
            </div>
          )}

          {/* Actions */}
          <div className="flex gap-3 flex-wrap pb-4">
            <button
              onClick={() => downloadRecipe(course)}
              className="font-['Space_Grotesk'] text-[11px] tracking-[0.1em] uppercase rounded-full px-5 py-2.5 cursor-pointer bg-transparent transition-colors"
              style={{
                color: p.text + "77",
                border: `1px solid ${p.text}15`,
              }}
            >
              &#8595; Download Recipe
            </button>
            {course.recipeSourceUrl && (
              <a
                href={course.recipeSourceUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="font-['Space_Grotesk'] text-[11px] tracking-[0.1em] uppercase no-underline rounded-full px-5 py-2.5 transition-colors"
                style={{
                  color: p.accent + "aa",
                  border: `1px solid ${p.accent}22`,
                }}
              >
                Full recipe &#8599;
              </a>
            )}
          </div>
        </div>
      </div>

      {/* Fixed bottom nav */}
      <div
        className="flex-shrink-0 px-6 py-4"
        style={{
          backgroundColor: "#080808",
          borderTop: `1px solid ${p.text}0a`,
        }}
      >
        <div className="max-w-2xl mx-auto flex items-center justify-between">
          <button
            onClick={() => navigate(-1)}
            disabled={currentIndex === 0}
            className="w-10 h-10 rounded-full flex items-center justify-center text-lg border-none cursor-pointer transition-opacity disabled:opacity-20"
            style={{
              backgroundColor: p.text + "10",
              color: p.text + "77",
            }}
          >
            &#8592;
          </button>
          <span
            className="font-['Space_Grotesk'] text-[11px] tracking-[0.1em]"
            style={{ color: p.text + "44" }}
          >
            {currentIndex + 1} of {courses.length}
          </span>
          <button
            onClick={() => navigate(1)}
            disabled={currentIndex === courses.length - 1}
            className="w-10 h-10 rounded-full flex items-center justify-center text-lg border-none cursor-pointer transition-opacity disabled:opacity-20"
            style={{
              backgroundColor: p.text + "10",
              color: p.text + "77",
            }}
          >
            &#8594;
          </button>
        </div>
      </div>
    </div>,
    document.body
  );
}
